language: python
python:
- '3.6'
services:
- docker

addons:
  apt:
    update: true
install:
- pip3 install -r requirements.txt
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t ipeirotis/census .
- docker push ipeirotis/census
  # - python3 restart_vm.py

